/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        background: '#ffffff',
        foreground: '#0a0a0a',
        card: '#ffffff',
        'card-foreground': '#0a0a0a',
        popover: '#ffffff',
        'popover-foreground': '#0a0a0a',
        primary: '#d92648',
        'primary-foreground': '#ffe1e1',
        secondary: '#f0f0f5',
        'secondary-foreground': '#191919',
        muted: '#f0f0f5',
        'muted-foreground': '#767676',
        accent: '#f0f0f5',
        'accent-foreground': '#191919',
        destructive: '#e60000',
        'destructive-foreground': '#fafafa',
        border: '#e5e5e5',
        input: '#e5e5e5',
        ring: '#d92648',
        'chart-1': '#e94522',
        'chart-2': '#30a387',
        'chart-3': '#356b7e',
        'chart-4': '#7be59b',
        'chart-5': '#fcd19d',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
      },
    },
  },
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#1b1b1b',
        foreground: '#f2f2f2',
        card: '#3c3c3c',
        'card-foreground': '#f2f2f2',
        popover: '#1a1a1a',
        'popover-foreground': '#f2f2f2',
        primary: '#d92648',
        'primary-foreground': '#ffe1e1',
        secondary: '#282828',
        'secondary-foreground': '#fafafa',
        muted: '#262626',
        'muted-foreground': '#a2a2a2',
        accent: '#282828',
        'accent-foreground': '#fafafa',
        destructive: '#993333',
        'destructive-foreground': '#ffd4d4',
        border: '#404040',
        input: '#404040',
        ring: '#d92648',
        'chart-1': '#4682b4',
        'chart-2': '#66cdaa',
        'chart-3': '#ff9933',
        'chart-4': '#9370db',
        'chart-5': '#d87093',
      },
    },
  },
};